#!/bin/sh

DOTFILES_DIR="$HOME/.dotfiles"
CONFIG_DIR="$HOME/.config"

mkdir -p "$CONFIG_DIR"

echo "Linking .dotfiles/.config to ~/.config..."
find "$DOTFILES_DIR/.config" -mindepth 1 -maxdepth 1 -exec sh -c '
for target; do
  link_name="$HOME/.config/$(basename "$target")"
  if [ -e "$link_name" ]; then
    echo "Skipping $link_name; already exists"
  else
    ln -s "$target" "$link_name"
    echo "Linked $target to $link_name"
  fi
done
' sh {} +

echo "Linking .dotfiles/* to ~/"
find "$DOTFILES_DIR" -mindepth 1 -maxdepth 1 ! -name 'README.md' ! -name 'LICENSE' ! -name '.git' ! -name 'deploy' ! -path "$DOTFILES_DIR/.config" -exec sh -c '
for target; do
  link_name="$HOME/$(basename "$target")"
  if [ -e "$link_name" ]; then
    echo "Skipping $link_name; already exists"
  else
    ln -s "$target" "$link_name"
    echo "Linked $target to $link_name"
  fi
done
' sh {} +
