#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# sudo not required for some system commands
for command in apt mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	z="zathura" \
	q="exit"

alias \
	magit="nvim -c MagitOnly" \

# Debian Package Management
alias \
	pkgin="sudo apt install -y" \
	pkgdel="sudo apt remove --purge -y" \
	pkgser="sudo apt search" \
	pkgclean="sudo apt autoremove -y" \

# VoidLinux Package Management
alias \
    xin="sudo xbps-install -Sy" \
    xser="sudo xbps-query -Rs" \
    xdel="sudo xbps-remove -y" \

# Tools
alias \
    szsh="source $HOME/.config/zsh/.zshrc" \
    szp="source $HOME/.zprofile" \

# Config files
alias \
    cf="cd $HOME/.config && ls -lAh" \
    cfv="vim $HOME/.config/nvim/init.vim" \
    cfa="vim $HOME/.config/shell/aliasrc" \
    cfz="vim $HOME/.config/zsh/.zshrc && szsh" \
    cfp="vim $HOME/.zprofile && szp" \
