######################
### KEY BINDING    ###
######################

# set prefix to Ctrl-space
unbind C-b
set -g prefix C-space
set -g default-terminal "tmux-256color"
set-option -g focus-events on
set -as terminal-features ",xterm*:RGB"

# force a reload of the config file
unbind r
bind C-r source-file "$HOME/.config/tmux/tmux.conf" \; display "Reloaded tmux conf"

# set window split
unbind v
unbind h
unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -c "#{pane_current_path}"

# pane selection
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# pane resize
bind -r Left  resize-pane -L 5
bind -r Down  resize-pane -D 5
bind -r Up    resize-pane -U 5
bind -r Right resize-pane -R 5

# pane movement to window
bind j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind s command-prompt -p "send pane to:"  "join-pane -t '%%'"

unbind a
bind a choose-tree -Zs

# Make a smaller delay so we can perform commands after switching windows
set -sg escape-time 0
set -sg repeat-time 600

# Window title begins by 1 and not 0
set -g base-index 1
setw -g pane-base-index 1

# window management
unbind n
unbind w
bind-key n command-prompt -p "name for new window:" "new-window -n '%%'"
bind-key r command-prompt "rename-window (%%)"
bind x kill-window
bind q killp

# panes
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# Scrollback lines
set -g history-limit 100000

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*.
setw -g aggressive-resize on

# enable mouse
set -g mouse on 

# Fzf-url
set -g @fzf-url-open "qutebrowser"
set -g @fzf-url-history-limit '2000'
set -g @fzf-url-extra-filter 'grep -oE "\b[a-zA-Z]+\.txt\b"'
set -g @fzf-url-fzf-options '-w 50% -h 50% --multi -0 --no-preview'

# List of plugins
TMUX_FZF_PREVIEW=0
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'furgelisherpa/kanagawa-tmux'

# Autoinstall TPM
if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
