-- core plugin configs --
require("core.plugins.autopairs")
require("core.plugins.autotag")
require("core.plugins.cmp")
require("core.plugins.colorizer")
require("core.plugins.colorscheme")
require("core.plugins.git")
require("core.plugins.lsp")
require("core.plugins.lualine")
require("core.plugins.multi")
require("core.plugins.nvimtree")
require("core.plugins.plugins")
require("core.plugins.telescope")
require("core.plugins.toggleterm")
require("core.plugins.treesitter")
require("core.plugins.whichkey")
