# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'all', 'devtools://*')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
c.content.headers.user_agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'

# Which method of blocking ads should be used.  Support for Adblock Plus
# (ABP) syntax blocklists using Brave's Rust library requires the
# `adblock` Python package to be installed, which is an optional
# dependency of qutebrowser. It is required when either `adblock` or
# `both` are selected.
# Type: String
# Valid values:
#   - auto: Use Brave's ABP-style adblocker if available, host blocking otherwise
#   - adblock: Use Brave's ABP-style adblocker
#   - hosts: Use hosts blocking
#   - both: Use both hosts blocking and Brave's ABP-style adblocker
c.content.blocking.method = 'both'

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow locally loaded documents to access remote URLs.
# Type: Bool
config.set('content.local_content_can_access_remote_urls', True, 'file:///home/pstivy/.local/share/qutebrowser/userscripts/*')

# Allow locally loaded documents to access other local URLs.
# Type: Bool
config.set('content.local_content_can_access_file_urls', False, 'file:///home/pstivy/.local/share/qutebrowser/userscripts/*')

# Proxy to use. In addition to the listed values, you can use a
# `socks://...` or `http://...` URL. Note that with QtWebEngine, it will
# take a couple of seconds until the change is applied, if this value is
# changed at runtime. Authentication for SOCKS proxies isn't supported
# due to Chromium limitations.
# Type: Proxy
# Valid values:
#   - system: Use the system wide proxy.
#   - none: Don't use any proxy
c.content.proxy = 'system'

# When to show the statusbar.
# Type: String
# Valid values:
#   - always: Always show the statusbar.
#   - never: Always hide the statusbar.
#   - in-mode: Show the statusbar when in modes other than normal mode.
c.statusbar.show = 'never'

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = 'bottom'

# When to show the tab bar.
# Type: String
# Valid values:
#   - always: Always show the tab bar.
#   - never: Always hide the tab bar.
#   - multiple: Hide the tab bar if only one tab is open.
#   - switching: Show the tab bar when switching tabs.
c.tabs.show = 'switching'

# Render all web contents using a dark theme. Example configurations
# from Chromium's `chrome://flags`: - "With simple HSL/CIELAB/RGB-based
# inversion": Set   `colors.webpage.darkmode.algorithm` accordingly, and
# set `colors.webpage.darkmode.policy.images` to `never`.  - "With
# selective image inversion": qutebrowser default settings.
# Type: Bool
c.colors.webpage.darkmode.enabled = True

# Bindings for normal mode
config.bind('M', 'hint links spawn mpv {hint-url}')

# Change the context menu theme
c.colors.contextmenu.disabled.fg = '#808080'
c.colors.contextmenu.menu.bg = '#353535'
c.colors.contextmenu.menu.fg = '#ffffff'
c.colors.contextmenu.selected.bg = '#909090'

# Define the palette
selenized_palette = {
    "bg_0":       "#103C48",
    "bg_1":       "#184956",
    "bg_2":       "#2D5B69",
    "dim_0":      "#72898F",
    "fg_0":       "#ADBCBC",
    "fg_1":       "#CAD8D9",
    "red":        "#fa5750",
    "green":      "#75b938",
    "yellow":     "#dbb32d",
    "blue":       "#4695f7",
    "magenta":    "#f275be",
    "cyan":       "#41c7b9",
    "orange":     "#ed8649",
    "violet":     "#af88eb",
    "br_red":     "#ff665c",
    "br_green":   "#84c747",
    "br_yellow":  "#ebc13d",
    "br_blue":    "#58a3ff",
    "br_magenta": "#ff84cd",
    "br_cyan":    "#53d6c7",
    "br_orange":  "#fd9456",
    "br_violet":  "#bd96fa",
}

# Prevent flake8 errors
c = c  # noqa: F821 pylint: disable=E0602,C0103
config = config  # noqa: F821 pylint: disable=E0602,C0103

# Completion background
c.colors.completion.category.bg = selenized_palette["bg_0"]
c.colors.completion.category.border.bottom = selenized_palette["bg_0"]
c.colors.completion.category.border.top = selenized_palette["bg_0"]
c.colors.completion.even.bg = selenized_palette["bg_0"]
c.colors.completion.odd.bg = selenized_palette["bg_0"]
c.colors.completion.item.selected.bg = selenized_palette["bg_1"]
c.colors.completion.item.selected.border.bottom = selenized_palette["bg_1"]
c.colors.completion.item.selected.border.top = selenized_palette["bg_1"]
c.colors.completion.scrollbar.bg = selenized_palette["bg_0"]

# Completion foreground
c.colors.completion.category.fg = selenized_palette["fg_1"]
c.colors.completion.fg = selenized_palette["fg_0"]
c.colors.completion.item.selected.fg = selenized_palette["fg_1"]
c.colors.completion.item.selected.match.fg = selenized_palette["red"]
c.colors.completion.match.fg = selenized_palette["orange"]
c.colors.completion.scrollbar.fg = selenized_palette["dim_0"]

# Download background
c.colors.downloads.bar.bg = selenized_palette["bg_0"]
c.colors.downloads.error.bg = selenized_palette["bg_0"]
c.colors.downloads.start.bg = selenized_palette["bg_0"]
c.colors.downloads.stop.bg = selenized_palette["bg_0"]

# Download foreground
c.colors.downloads.error.fg = selenized_palette["red"]
c.colors.downloads.start.fg = selenized_palette["fg_0"]
c.colors.downloads.stop.fg = selenized_palette["fg_0"]

# Hint colors
c.colors.hints.bg = selenized_palette["bg_0"]
c.hints.border = "1px solid" + selenized_palette["bg_1"]
c.colors.hints.fg = selenized_palette["fg_0"]
c.colors.hints.match.fg = selenized_palette["fg_1"]

# Keyhint colors
c.colors.keyhint.bg = selenized_palette["bg_0"]
c.colors.keyhint.fg = selenized_palette["fg_0"]
c.colors.keyhint.suffix.fg = selenized_palette["fg_1"]

# Message background
c.colors.messages.error.bg = selenized_palette["bg_0"]
c.colors.messages.error.border = selenized_palette["bg_0"]
c.colors.messages.info.bg = selenized_palette["bg_0"]
c.colors.messages.info.border = selenized_palette["bg_0"]
c.colors.messages.warning.bg = selenized_palette["bg_0"]
c.colors.messages.warning.border = selenized_palette["bg_0"]

# Message Foreground
c.colors.messages.error.fg = selenized_palette["red"]
c.colors.messages.info.fg = selenized_palette["fg_0"]
c.colors.messages.warning.fg = selenized_palette["orange"]

# Prompt colors
c.colors.prompts.bg = selenized_palette["bg_0"]
c.colors.prompts.border = "1px solid" + selenized_palette["bg_0"]
c.colors.prompts.fg = selenized_palette["fg_0"]
c.colors.prompts.selected.bg = selenized_palette["bg_1"]

# Status bar background
c.colors.statusbar.caret.bg = selenized_palette["bg_0"]
c.colors.statusbar.caret.selection.bg = selenized_palette["bg_0"]
c.colors.statusbar.command.bg = selenized_palette["bg_0"]
c.colors.statusbar.command.private.bg = selenized_palette["bg_0"]
c.colors.statusbar.insert.bg = selenized_palette["bg_0"]
c.colors.statusbar.normal.bg = selenized_palette["bg_0"]
c.colors.statusbar.passthrough.bg = selenized_palette["bg_0"]
c.colors.statusbar.private.bg = selenized_palette["bg_0"]
c.colors.statusbar.progress.bg = selenized_palette["fg_0"]

# Status bar foreground
c.colors.statusbar.caret.fg = selenized_palette["magenta"]
c.colors.statusbar.caret.selection.fg = selenized_palette["magenta"]
c.colors.statusbar.command.fg = selenized_palette["fg_0"]
c.colors.statusbar.command.private.fg = selenized_palette["fg_0"]
c.colors.statusbar.insert.fg = selenized_palette["orange"]
c.colors.statusbar.normal.fg = selenized_palette["fg_0"]
c.colors.statusbar.passthrough.fg = selenized_palette["br_orange"]
c.colors.statusbar.private.fg = selenized_palette["fg_0"]
c.colors.statusbar.url.error.fg = selenized_palette["red"]
c.colors.statusbar.url.fg = selenized_palette["fg_0"]
c.colors.statusbar.url.hover.fg = selenized_palette["blue"]
c.colors.statusbar.url.success.http.fg = selenized_palette["green"]
c.colors.statusbar.url.success.https.fg = selenized_palette["green"]
c.colors.statusbar.url.warn.fg = selenized_palette["orange"]

# Tab bar background
c.colors.tabs.bar.bg = selenized_palette["bg_2"]
c.colors.tabs.even.bg = selenized_palette["bg_2"]
c.colors.tabs.odd.bg = selenized_palette["bg_2"]
c.colors.tabs.pinned.even.bg = selenized_palette["blue"]
c.colors.tabs.pinned.odd.bg = selenized_palette["blue"]
c.colors.tabs.pinned.selected.even.bg = selenized_palette["bg_0"]
c.colors.tabs.pinned.selected.odd.bg = selenized_palette["bg_0"]
c.colors.tabs.selected.even.bg = selenized_palette["bg_0"]
c.colors.tabs.selected.odd.bg = selenized_palette["bg_0"]

# Tab bar foreground
c.colors.tabs.even.fg = selenized_palette["fg_0"]
c.colors.tabs.odd.fg = selenized_palette["fg_0"]
c.colors.tabs.pinned.even.fg = selenized_palette["fg_0"]
c.colors.tabs.pinned.odd.fg = selenized_palette["fg_0"]
c.colors.tabs.pinned.selected.even.fg = selenized_palette["fg_1"]
c.colors.tabs.pinned.selected.odd.fg = selenized_palette["fg_1"]
c.colors.tabs.selected.even.fg = selenized_palette["fg_1"]
c.colors.tabs.selected.odd.fg = selenized_palette["fg_1"]

# Tab indicator
c.colors.tabs.indicator.error = selenized_palette["red"]
c.colors.tabs.indicator.start = selenized_palette["green"]
c.colors.tabs.indicator.stop = selenized_palette["green"]

# Loading background
c.colors.webpage.bg = selenized_palette["fg_0"]

